In [1]:
import pandas as pd
import numpy as np
from os import listdir
import re

# Parsing

In [2]:
def CompileCSV(FOLDER : str):
    FILENAMES = [f'{FOLDER}/{file}' for file in listdir(FOLDER)[1:]]
    FILENAMES
    
    output = None
    
    for f in FILENAMES:
        if f[-4:] != '.csv':
            break
    
        df = None
    
        YEAR, SEASON = f.split('/')[-1].strip('.csv').split('_')
        #print(YEAR, SEASON)
    
        df = pd.read_csv(f).drop(columns='Unnamed: 0')
        df['Year'] = YEAR
        df['Season'] = SEASON
    
    
        if output is None:
            output = df.copy()
        else:
            output = pd.concat([output, df])

    return output

In [3]:
df_ids = CompileCSV('../Scraping/Season')
df_ids['MAL_id'] = df_ids.Link.str.extract(r'myanimelist.net/anime/(\d+)').astype(int)
df_ids.head()

,Title,Link,Year,Season,MAL_id
0,Shinseiki Evangelion,https://myanimelist.net/anime/30/Shinseiki_Eva...,1995,fall,30
1,Gokinjo Monogatari,https://myanimelist.net/anime/852/Gokinjo_Mono...,1995,fall,852
2,Bakuretsu Hunters,https://myanimelist.net/anime/495/Bakuretsu_Hu...,1995,fall,495
3,Kaitou Saint Tail,https://myanimelist.net/anime/1567/Kaitou_Sain...,1995,fall,1567
4,Shinpi no Sekai El-Hazard (TV),https://myanimelist.net/anime/116/Shinpi_no_Se...,1995,fall,116

In [4]:
df = CompileCSV('../Scraping/Detail/')
df_ids = df_ids.drop_duplicates('MAL_id')
df = pd.merge(df, df_ids[['Title', 'MAL_id']], on='Title', how='left')
df = df.set_index('MAL_id')

df = df.drop(columns=['Synonyms', 'Japanese', 'English', 'German', 'Spanish', 'French', 'Aired', 'Synopsis','Broadcast','Premiered'])
df.head(3).T

MAL_id,40748,40776,41389
Type,['TV'],['TV'],['TV']
Episodes,24,12,12
Status,Finished Airing,Finished Airing,Finished Airing
Producers,"['Mainichi Broadcasting System', 'TOHO animati...","['Dentsu', 'Mainichi Broadcasting System', 'Mo...","['Shogakukan-Shueisha Productions', 'Warner Br..."
Licensors,['VIZ Media'],['Sentai Filmworks'],['Anime Limited']
Studios,['MAPPA'],['Production I.G'],['Seven Arcs']
Source,['Manga'],['Manga'],['Manga']
Genres,"['Action', 'Award Winning', 'Supernatural']",NaN,"['Comedy', 'Romance']"
Theme,['School'],NaN,NaN
Demographic,['Shounen'],['Shounen'],['Shounen']
Duration,23 min. per ep.,23 min. per ep.,23 min. per ep.
Rating,R - 17+ (violence & profanity),PG-13 - Teens 13 or older,PG-13 - Teens 13 or older
Score,8.57,8.55,7.86
Ranked,#109,#124,#912
Popularity,#13,#219,#264
Members,"2,740,023","863,774","783,366"
Favorites,"93,063","6,318","10,209"
Scorers,1798795.0,513859.0,440794.0
Related_Entries,"['Prequel (Movie) Jujutsu Kaisen 0 Movie', 'Se...","['Prequel (TV) Haikyuu!! To the Top', 'Sequel ...","['Sequel (OVA) Tonikaku Kawaii: SNS', 'Adaptat..."
Title,Jujutsu Kaisen,Haikyuu!! To the Top Part 2,Tonikaku Kawaii
Genre,NaN,['Sports'],NaN
Themes,NaN,"['School', 'Team Sports']",NaN
Demographics,NaN,NaN,NaN
Year,2020,2020,2020
Season,fall,fall,fall

In [5]:
def ExtractList(col : str):
    df[col] = df[col].str.findall(r"'([^']*)'")

for c in ['Producers', 'Licensors', 'Studios', 'Themes', 'Theme', 'Genres', 'Genre', 'Demographics', 'Demographic']:
    ExtractList(c)

In [6]:
def ExtractFirstItemInList(col : str):
    df[col] = df[col].str.extract(r"'([^']*)'")
    
for c in ['Source', 'Type']:
    ExtractFirstItemInList(c)

In [7]:
df['Episodes'] = df['Episodes'].replace('Unknown', np.nan).astype(float)

In [8]:
df['Is_Finished'] = df.Status == 'Finished Airing'
df = df.drop(columns=['Status'])

In [9]:
ExtractList('Related_Entries')
df['Related_Entries'] = df['Related_Entries'].apply(lambda x : len(x))

In [10]:
df['Year'] = df['Year'].astype(int)
df['Members'] = df['Members'].replace(',','', regex=True).astype(int)
df['Favorites'] = df['Favorites'].replace(',','', regex=True).astype(int)

In [11]:
df['Score'] = df['Score'].replace('[]', np.nan).astype(float)

In [12]:
df['Scorers'] = df['Scorers'].replace(np.nan, 0).astype(int)

In [13]:
df['Ranked'] = df['Ranked'].replace('#', '', regex=True).astype(float)
df['Popularity'] = df['Popularity'].replace('#', '', regex=True).astype(int)

In [14]:
df['Themes'] = df['Theme'].combine_first(df['Themes'])
df['Genres'] = df['Genre'].combine_first(df['Genres'])
df['Demographics'] = df['Demographic'].combine_first(df['Demographics'])
df = df.drop(columns=['Theme', 'Genre', 'Demographic'])

In [15]:
def ExtractMinutes(time_str : str):
    hours_match = re.search(r'(\d+)\s*hr', time_str)
    minutes_match = re.search(r'(\d+)\s*min', time_str)

    minutes = 0
    if hours_match:
        minutes += int(hours_match.group(1)) * 60
    if minutes_match:
        minutes += int(minutes_match.group(1)) 

    return minutes

df['Duration'] = df['Duration'].apply(lambda x: ExtractMinutes(str(x)))

In [16]:
df.head().T

MAL_id,40748,40776,41389,40454,41433
Type,TV,TV,TV,TV,TV
Episodes,24.0,12.0,12.0,12.0,12.0
Producers,"[Mainichi Broadcasting System, TOHO animation,...","[Dentsu, Mainichi Broadcasting System, Movic, ...","[Shogakukan-Shueisha Productions, Warner Bros....","[Movic, Warner Bros. Japan, KlockWorx, Hakuhod...","[Marvelous Entertainment, Yomiko Advertising, ..."
Licensors,[VIZ Media],[Sentai Filmworks],[Anime Limited],[Sentai Filmworks],[Funimation]
Studios,[MAPPA],[Production I.G],[Seven Arcs],[J.C.Staff],[Pierrot]
Source,Manga,Manga,Manga,Light novel,NaN
Genres,"[Action, Award Winning, Supernatural]",[Sports],"[Comedy, Romance]","[Action, Adventure, Fantasy]","[Action, Sci-Fi, Suspense]"
Duration,23,23,23,23,24
Rating,R - 17+ (violence & profanity),PG-13 - Teens 13 or older,PG-13 - Teens 13 or older,PG-13 - Teens 13 or older,R - 17+ (violence & profanity)
Score,8.57,8.55,7.86,7.46,7.58
Ranked,109.0,124.0,912.0,2105.0,1637.0
Popularity,13,219,264,357,523
Members,2740023,863774,783366,638294,458195
Favorites,93063,6318,10209,1933,3875
Scorers,1798795,513859,440794,332460,212570
Related_Entries,4,4,2,4,0
Title,Jujutsu Kaisen,Haikyuu!! To the Top Part 2,Tonikaku Kawaii,Dungeon ni Deai wo Motomeru no wa Machigatteir...,Akudama Drive
Themes,[School],"[School, Team Sports]",NaN,NaN,"[Adult Cast, Gore]"
Demographics,[Shounen],[Shounen],[Shounen],NaN,NaN
Year,2020,2020,2020,2020,2020
Season,fall,fall,fall,fall,fall
Is_Finished,True,True,True,True,True

In [17]:
df.dtypes

Type                object
Episodes           float64
Producers           object
Licensors           object
Studios             object
Source              object
Genres              object
Duration             int64
Rating              object
Score              float64
Ranked             float64
Popularity           int64
Members              int64
Favorites            int64
Scorers              int64
Related_Entries      int64
Title               object
Themes              object
Demographics        object
Year                 int64
Season              object
Is_Finished           bool
dtype: object

In [18]:
df.to_csv('Cleaned.csv')

# Utility Matrix

In [19]:
def OneHotList(input_df, col, prefix):
    output = input_df[[col]]

    output = output.fillna('FILLNA')
    
    for i in output[col].explode().unique():
        output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)

    if f'{prefix}FILLNA' in output.columns:
        output = output.drop(columns=[f'{prefix}FILLNA'])

    output = output.drop(columns=[col])
    return output

In [20]:
USM = df[['Title', 'Is_Finished']].copy()
USM['Is_Finished'] = USM['Is_Finished'].astype(np.int8)

items = [('Genres', 'Genre_'),
         ('Demographics', 'Demo_'),
         ('Themes', 'Theme_'),
         ('Studios', 'Studio_'),
         ('Producers', 'Producer_'),
         ('Licensors', 'Licensor_'),
        ]

for i in items:      
    USM = pd.concat(axis=1, objs= [USM, OneHotList(df, i[0], i[1])])

C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_18804\2727251450.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  output[f'{prefix}{i}'] = output[col].apply(lambda x: 1 if i in x else 0)

In [21]:
df.reset_index()[df.reset_index().MAL_id == 40776]

,MAL_id,Type,Episodes,Producers,Licensors,Studios,Source,Genres,Duration,Rating,...,Members,Favorites,Scorers,Related_Entries,Title,Themes,Demographics,Year,Season,Is_Finished
1,40776,TV,12.0,"[Dentsu, Mainichi Broadcasting System, Movic, ...",[Sentai Filmworks],[Production I.G],Manga,[Sports],23,PG-13 - Teens 13 or older,...,863774,6318,513859,4,Haikyuu!! To the Top Part 2,"[School, Team Sports]",[Shounen],2020,fall,True

In [22]:
items = [
    ['Type', 'Type'],
    ['Rating', 'Rating'],
    ['Source', 'Source'],
]

for i in items:      
    USM = pd.concat(axis=1, objs= [USM, 
                                   pd.get_dummies(df[i[0]], prefix=i[1]).astype(np.int8)])

In [23]:
USM

,Title,Is_Finished,Genre_Action,Genre_Award Winning,Genre_Supernatural,Genre_Sports,Genre_Comedy,Genre_Romance,Genre_Adventure,Genre_Fantasy,...,Rating_G - All Ages,Rating_PG - Children,Rating_PG-13 - Teens 13 or older,Rating_R - 17+ (violence & profanity),Rating_R+ - Mild Nudity,Rating_Rx - Hentai,Source_4-koma manga,Source_Light novel,Source_Manga,Source_Web manga
MAL_id,,,,,,,,,,,,,,,,,,,,,
40748,Jujutsu Kaisen,1,1,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
40776,Haikyuu!! To the Top Part 2,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
41389,Tonikaku Kawaii,1,0,0,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,1,0
40454,Dungeon ni Deai wo Motomeru no wa Machigatteir...,1,1,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,1,0,0
41433,Akudama Drive,1,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58606,Girls & Panzer: Saishuushou Part 4 Specials,1,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
58006,Science SARU x MBS Original Short Anime Daisak...,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
58229,Harutsugeuo to Fuuraibou,1,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
58605,Moja to Majo (TV Special),1,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
58308,Hakofugu to Minamata no Umi,1,0,0,0,0,0,0,1,1,...,1,0,0,0,0,0,0,0,0,0

In [24]:
USM.to_csv('USM.csv')