In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Files/VA_Records.csv')
df = df.drop(columns=['Unnamed: 0'])

In [3]:
df

,Anime_ID,Title,Type,Season,Year,Character,Character_ID,Character_Favorites,Personnel_ID,Personnel_Name,Role_Main,Role_Supporting
0,3588,Soul Eater,TV,Spring,2008.0,Excalibur,13046,1574,10002,Rajkai Zoltán,False,True
1,27,Trinity Blood,TV,Spring,2005.0,"Nightroad, Abel",1672,974,10002,Rajkai Zoltán,True,False
2,20,Naruto,TV,Fall,2002.0,"Gekkou, Hayate",7738,54,10002,Rajkai Zoltán,False,True
3,47,Akira,Movie,NaN,1988.0,Yamagata,20463,13,10002,Rajkai Zoltán,False,True
4,523,Tonari no Totoro,Movie,NaN,1988.0,"Kusakabe, Tatsuo",8047,25,10002,Rajkai Zoltán,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
281008,530,Bishoujo Senshi Sailor Moon,TV,Spring,1992.0,"Tsukino, Usagi",2030,5623,9,Mitsuishi Kotono,True,False
281009,8215,Genji Tsuushin Agedama,TV,Fall,1991.0,"Heike, Ibuki",86545,1,9,Mitsuishi Kotono,True,False
281010,1762,Arslan Senki,OVA,NaN,1991.0,Etoile,82891,43,9,Mitsuishi Kotono,False,True
281011,1391,Future GPX Cyber Formula,TV,Spring,1991.0,"Sugo, Asuka",2389,14,9,Mitsuishi Kotono,True,False
281012,820,Ginga Eiyuu Densetsu,OVA,NaN,1988.0,"von Kreutzer, Katerose",13857,18,9,Mitsuishi Kotono,False,True

In [4]:
df_Filtering = df[['Personnel_ID', 'Personnel_Name']].drop_duplicates()

In [5]:
def countVowels(s):
    vowels = "aeiouAEIOU"
    vowel_count = 0

    invalids = "lxvqLXVQáéíóúàèìòùäëïöüâêîôûãõæœAEIOUÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛÃÕÆŒñçšžłćđŋđ"
    
    for char in s:
        if char in vowels:
            vowel_count += 1
        if char in invalids:
            return -999
            
    return vowel_count

In [6]:
def countLetters(string):
    return len(''.join(string.split()))

In [7]:
def countConsecutiveConsonants(s):
    vowels = 'aeiouAEIOU'

    
    # Initialize variables
    count = 0
    max_count = 0
    in_consonant_sequence = False
    
    # Iterate through each character in the string
    for char in s:
        # Check if the character is a consonant
        if char.isalpha() and char not in vowels:
            count += 1
            in_consonant_sequence = True
        else:
            # If a sequence ends, update max_count
            if in_consonant_sequence:
                max_count = max(max_count, count)
            count = 0  # Reset count for next sequence
            in_consonant_sequence = False
    
    # Final check in case the string ends with a consonant sequence
    if in_consonant_sequence:
        max_count = max(max_count, count)
    
    return max_count

In [8]:
df_Filtering['Vowel_Count'] = df_Filtering.Personnel_Name.apply(countVowels)
df_Filtering['Letter_Count'] = df_Filtering.Personnel_Name.apply(countLetters)
df_Filtering['Vowel_Percentage'] = df_Filtering.Vowel_Count / df_Filtering.Letter_Count
df_Filtering['Consecutive_Consonants'] = df_Filtering.Personnel_Name.apply(countConsecutiveConsonants)

In [9]:
df_Filtering = df_Filtering[df_Filtering.Consecutive_Consonants <= 3].sort_values('Consecutive_Consonants')
df_Filtering

,Personnel_ID,Personnel_Name,Vowel_Count,Letter_Count,Vowel_Percentage,Consecutive_Consonants
91879,23805,Nomura Mayuka,6,12,0.500000,1
91725,237,Kosugi Juurouta,8,14,0.571429,1
91703,23797,Hagen Josefin,5,12,0.416667,1
91654,23793,Di Pofi Federico,7,14,0.500000,1
91211,23713,Hoover Natalie,-999,13,-76.846154,1
...,...,...,...,...,...,...
91353,23731,Mete Andrea,-999,10,-99.900000,3
91072,23707,Simon Bernd,3,10,0.300000,3
279558,9959,Goldberg Marcy,-999,13,-76.846154,3
279495,9948,Szombathy Jerry,3,14,0.214286,3
1034,10047,Niosi Chri,4,9,0.444444,3

In [13]:
df_Filtering = df_Filtering[df_Filtering.Vowel_Percentage > 0.42].sort_values('Vowel_Percentage')
df_Filtering

,Personnel_ID,Personnel_Name,Vowel_Count,Letter_Count,Vowel_Percentage,Consecutive_Consonants
25511,12240,Takashina Toshitsugu,8,19,0.421053,2
653,10022,Shimoyama Yoshimitsu,8,19,0.421053,2
208680,56068,Darah MarieChristine,8,19,0.421053,3
80780,21161,Matsuzaki Katsutoshi,8,19,0.421053,2
154146,43318,Fiorentini Francesca,8,19,0.421053,2
...,...,...,...,...,...,...
183532,48466,Nao,2,3,0.666667,1
165064,44485,Mei,2,3,0.666667,1
85196,217,Saitou Rie,6,9,0.666667,1
117942,31801,Hakuei,4,6,0.666667,1
186172,50147,Maia,3,4,0.750000,1

In [14]:
df = df[df.Personnel_ID.apply(lambda x : x in df_Filtering.Personnel_ID.values)]
df.to_csv('Files/VA_Records_JP.csv')
df

,Anime_ID,Title,Type,Season,Year,Character,Character_ID,Character_Favorites,Personnel_ID,Personnel_Name,Role_Main,Role_Supporting
98,721,Princess Tutu,TV,Summer,2002.0,Drosselmeyer,1053,60,10007,Noboru Mitani,False,True
247,60551,Hyakushou Kizoku 3rd Season,TV,Fall,2025.0,"Arakawa, Hiromu",228789,2,10013,Tamura Mutsumi,True,False
248,59897,Kobayashi-san Chi no Maid Dragon: Samishigariy...,Movie,NaN,2025.0,Kobayashi,136726,3090,10013,Tamura Mutsumi,True,False
249,51818,Enen no Shouboutai: San no Shou,TV,Spring,2025.0,"Son, Nataku",179670,4,10013,Tamura Mutsumi,False,True
250,57827,Mashin Souzouden Wataru,TV,Winter,2025.0,"Hoshibe, Wataru",255081,1,10013,Tamura Mutsumi,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
281008,530,Bishoujo Senshi Sailor Moon,TV,Spring,1992.0,"Tsukino, Usagi",2030,5623,9,Mitsuishi Kotono,True,False
281009,8215,Genji Tsuushin Agedama,TV,Fall,1991.0,"Heike, Ibuki",86545,1,9,Mitsuishi Kotono,True,False
281010,1762,Arslan Senki,OVA,NaN,1991.0,Etoile,82891,43,9,Mitsuishi Kotono,False,True
281011,1391,Future GPX Cyber Formula,TV,Spring,1991.0,"Sugo, Asuka",2389,14,9,Mitsuishi Kotono,True,False
281012,820,Ginga Eiyuu Densetsu,OVA,NaN,1988.0,"von Kreutzer, Katerose",13857,18,9,Mitsuishi Kotono,False,True